dependencies:
  node:
    version: "16.15.1" # Keep in sync with phoenix_static_buildpack.config, .nvmrc
    checksum: "308aee7149c4092a53c87c28ef49e23a8d1606119e79ae68333062e2a1f94208"

docker_services:
  postgres:
    image: "postgres:13.6-alpine"
    version: "13.6" # Keep in sync with .github/workflows/ci.yml
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex-remit/postgres:/var/lib/postgresql/data --shm-size=1gb"
